/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    DialogContactoEmpresa: typeof import('./src/components/empresas/DialogContactoEmpresa.vue')['default']
    DialogDetallesAlumno: typeof import('./src/components/alumnos/DialogDetallesAlumno.vue')['default']
    DialogDetallesEmpresa: typeof import('./src/components/empresas/DialogDetallesEmpresa.vue')['default']
    DialogDetallesFCT: typeof import('./src/components/fct/DialogDetallesFCT.vue')['default']
    DialogDetallesTutor: typeof import('./src/components/tutores/DialogDetallesTutor.vue')['default']
    DialogDetallesUsuario: typeof import('./src/components/usuarios/DialogDetallesUsuario.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomePanel: typeof import('./src/components/home/WelcomePanel.vue')['default']
  }
}
