/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlumnosPage: typeof import('./src/components/alumnos/AlumnosPage.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogContactoEmpresa: typeof import('./src/components/empresas/DialogContactoEmpresa.vue')['default']
    DialogCrearAlumno: typeof import('./src/components/alumnos/DialogCrearAlumno.vue')['default']
    DialogCrearEmpresa: typeof import('./src/components/empresas/DialogCrearEmpresa.vue')['default']
    DialogCrearFCT: typeof import('./src/components/fct/DialogCrearFCT.vue')['default']
    DialogCrearTutorCentro: typeof import('./src/components/tutoresCentro/DialogCrearTutorCentro.vue')['default']
    DialogCrearTutorEmpresa: typeof import('./src/components/tutoresEmpresa/DialogCrearTutorEmpresa.vue')['default']
    DialogCrearUsuario: typeof import('./src/components/usuarios/DialogCrearUsuario.vue')['default']
    DialogDetallesAlumno: typeof import('./src/components/alumnos/DialogDetallesAlumno.vue')['default']
    DialogDetallesEmpresa: typeof import('./src/components/empresas/DialogDetallesEmpresa.vue')['default']
    DialogDetallesFCT: typeof import('./src/components/fct/DialogDetallesFCT.vue')['default']
    DialogDetallesTutor: typeof import('./src/components/tutoresCentro/DialogDetallesTutor.vue')['default']
    DialogDetallesTutorCentro: typeof import('./src/components/tutoresCentro/DialogDetallesTutorCentro.vue')['default']
    DialogDetallesTutorEmpresa: typeof import('./src/components/tutoresEmpresa/DialogDetallesTutorEmpresa.vue')['default']
    DialogDetallesUsuario: typeof import('./src/components/usuarios/DialogDetallesUsuario.vue')['default']
    DialogUpdateAlumno: typeof import('./src/components/alumnos/DialogUpdateAlumno.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    EmpresasPage: typeof import('./src/components/empresas/EmpresasPage.vue')['default']
    FCTPage: typeof import('./src/components/fct/FCTPage.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    HomePage: typeof import('./src/components/home/HomePage.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    PerfilPage: typeof import('./src/components/PerfilPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TutoresCentroPage: typeof import('./src/components/tutoresCentro/TutoresCentroPage.vue')['default']
    TutoresEmpresaPage: typeof import('./src/components/tutoresEmpresa/TutoresEmpresaPage.vue')['default']
    UsuariosPage: typeof import('./src/components/usuarios/UsuariosPage.vue')['default']
    WelcomePanel: typeof import('./src/components/home/WelcomePanel.vue')['default']
  }
}
