services:
  db:
    image: mariadb:lts
    container_name: naga-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - naga-db:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - naga-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    container_name: naga-springboot
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - naga-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
        - VITE_BASE_URL=${FRONTEND_BASE_URL}
    env_file:
      - .env
    container_name: naga-vue
    ports:
      - 6321:80
    networks:
      - naga-network

networks:
  naga-network:
    name: naga-network
    driver: bridge
  

volumes:
  naga-db:
    name: naga-db
