services:
  db:
    build:
      context: ./db
    container_name: fct-postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - fct-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fct-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fct-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - fct-network

  backend:
    build:
      context: ./backend
    container_name: fct-backend-springboot
    ports:
      - 8081:9000
    networks:
      - fct-network

  frontend:
    build:
      context: ./frontend
    container_name: fct-frontend-vue
    ports:
      - 6321:80
    networks:
      - fct-network

networks:
  fct-network:
    name: fct-network
    driver: bridge

volumes:
  fct-db:
    name: fct-db
