services:
  db:
    image: mariadb:lts
    container_name: fct-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - fct-db:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 3306:3306
    networks:
      - fct-network

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: fct-phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - fct-network

  backend:
    build:
      context: ./backend
    container_name: fct-backend-springboot
    ports:
      - 9000:9000
    networks:
      - fct-network

  frontend:
    build:
      context: ./frontend
    container_name: fct-frontend-vue
    ports:
      - 4171:80
    networks:
      - fct-network

networks:
  fct-network:
    name: fct-network
    driver: bridge

volumes:
  fct-db:
    name: fct-db
