Table concellos {
    id bigint [pk, unique]
    nombre varchar(500) [not null]
}

Table especialidades {
    id serial [pk, unique]
    nombre varchar(500) [not null]
}

Table estados_alumnos {
    id serial [pk, unique]
    nombre varchar(500) [not null]
}

Table roles_usuarios {
    id serial [pk, unique]
    nombre varchar(500) [not null]
}


Table alumnos {
    id bigserial [pk]
    dni_nie bigint [unique, not null]
    nombre varchar(500) [not null]
    apellidos varchar(500) [not null]
    curso_id int [not null]
    email varchar(500) [not null]
    telefono varchar(500) [not null]
    concello_id bigint [not null]
    numero_seguridad_social bigint [unique]
    estado_id int [not null]
    tutor_empresa_id bigint
    tutor_centro_id bigint [not null]
}

Table correos {
    id bigint [pk, unique]
    fecha date [not null]
    usuario_id bigint [not null]
    empresa_id bigint [not null]
    curso_academico varchar(50) [not null]
}

Table empresas {
    id bigint [pk, unique]
    nombre varchar(500) [not null]
    concello_id bigint [not null]
    direccion varchar(500) [not null]
    observaciones text
    especialidad_id int [not null]
    contacto_nombre varchar(500)
    contacto_email varchar(500)
    contacto_telefono varchar(500)
    disponible boolean [not null]
    plazas smallint [default: 0]
}

Table skills {
    id bigint [pk, unique]
    nombre varchar(500) [not null]
    especialidad_id int [not null]
}

Table tutores_centro {
    id bigint [pk, unique]
    nombre varchar(500) [not null]
    apellidos varchar(500) [not null]
    email varchar(500) [not null]
    curso_id int [not null]
    activo boolean [not null]
}

Table tutores_empresa {
    id bigint [pk, unique]
    empresa_id bigint [not null]
    nombre varchar(500) [not null]
    apellidos varchar(500) [not null]
    email varchar(500) [not null]
    telefono varchar(500) [not null]
}

Table usuarios {
    id serial [pk, unique]
    email varchar(500) [not null, unique]
    password varchar(500) [not null]
    rol_id int [not null]
    tutor_id bigint
    activo boolean [not null]
}


Table alumnos_empresas {
    id bigint [pk, unique]
    alumno_id bigint [not null]
    empresa_id bigint [not null]
    fecha_inicio date [not null]
    fecha_fin date
}

Table empresas_skills {
    id bigint [pk, unique]
    empresa_id bigint [not null]
    skill_id bigint [not null]
}


Ref: "alumnos"."concello_id" > "concellos"."id"
Ref: "alumnos"."estado_id" > "estados_alumnos"."id"
Ref: "alumnos"."tutor_empresa_id" > "tutores_empresa"."id"
Ref: "alumnos"."tutor_centro_id" > "tutores_centro"."id"

Ref: "skills"."especialidad_id" > "especialidades"."id"

Ref: "empresas"."concello_id" > "concellos"."id"
Ref: "empresas"."especialidad_id" > "especialidades"."id"

Ref: "empresas_skills"."empresa_id" > "empresas"."id"
Ref: "empresas_skills"."skill_id" > "skills"."id"

Ref: "tutores_empresa"."empresa_id" > "empresas"."id"

Ref: "usuarios"."rol_id" > "roles_usuarios"."id"
Ref: "usuarios"."tutor_id" > "tutores_centro"."id"

Ref: "alumnos_empresas"."alumno_id" > "alumnos"."id"
Ref: "alumnos_empresas"."empresa_id" > "empresas"."id"

Ref: "correos"."usuario_id" > "usuarios"."id"
Ref: "correos"."empresa_id" > "empresas"."id"
