name: Build and Push Docker Images (Manual)

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version to generate Docker images (ej: 1.0.0)"
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.release_version }}
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{github.repository}}-backend:${{ github.event.inputs.release_version }}
            ghcr.io/${{github.repository}}-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{github.repository}}-frontend:${{ github.event.inputs.release_version }}
            ghcr.io/${{github.repository}}-frontend:latest
